<a href="https://colab.research.google.com/github/ARNAVKS/spam-email-classifier/blob/main/Spam_Classifier_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
table = pd.read_csv('completeSpamAssassin.csv')

In [ ]:
table.head()

Unnamed: 0                                               Body  Label
0           0  \nSave up to 70% on Life Insurance.\nWhy Spend...      1
1           1  1) Fight The Risk of Cancer!\nhttp://www.adcli...      1
2           2  1) Fight The Risk of Cancer!\nhttp://www.adcli...      1
3           3  ##############################################...      1
4           4  I thought you might like these:\n1) Slim Down ...      1

In [ ]:
len(table)

6046

In [ ]:
table['Label'].value_counts()

Label
0    4150
1    1896
Name: count, dtype: int64

In [ ]:
#dropping the irrelevent column(s)

table.drop(columns='Unnamed: 0', axis=1,inplace=True)

In [ ]:
table.head()

Body  Label
0  \nSave up to 70% on Life Insurance.\nWhy Spend...      1
1  1) Fight The Risk of Cancer!\nhttp://www.adcli...      1
2  1) Fight The Risk of Cancer!\nhttp://www.adcli...      1
3  ##############################################...      1
4  I thought you might like these:\n1) Slim Down ...      1

In [ ]:
#importing regular expression library
import re

In [ ]:
#making a compiler for replacing url

remove_url = re.compile(r'https?://\S+|www\.\S+')

In [ ]:
#changing all the data in the Body column into string type

table['Body']=table['Body'].apply(lambda x:str(x))

In [ ]:
#lowercasing all the data in the Body column

table['Body']=table['Body'].apply(lambda x:x.lower())

In [ ]:
#making another compiler for removing the newline character '\n'

newline_rem=re.compile(r'\n')

In [ ]:
#checking the compiler if its replacing the '\n' or not

tet='\nsaveup'
newline_rem.sub('',tet)

'saveup'

In [ ]:
#now using compiler for removing all the '\n' character in all the data in the Body column

table['Body']=table['Body'].apply(lambda x:newline_rem.sub('',x))

In [ ]:
table.head()

Body  Label
0  save up to 70% on life insurance.why spend mor...      1
1  1) fight the risk of cancer!http://www.adclick...      1
2  1) fight the risk of cancer!http://www.adclick...      1
3  ##############################################...      1
4  i thought you might like these:1) slim down - ...      1

In [ ]:
#using the 'remove_url' compiler for removing the url in the Body column data if url is there in the data

table['Body']=table['Body'].apply(lambda x:remove_url.sub('',x))

In [ ]:
table.head()

Body  Label
0  save up to 70% on life insurance.why spend mor...      1
1  1) fight the risk of cancer! slim down - guara...      1
2  1) fight the risk of cancer! slim down - guara...      1
3  ##############################################...      1
4  i thought you might like these:1) slim down - ...      1

In [ ]:
#Making a compiler for removing @ and changing a email id into a normal text

mail_rem=re.compile(r'[^\@]\@[^\@]')

In [ ]:
#Applying the 'mail_rem' compiler for changing email-id into normal text

table['Body']=table['Body'].apply(lambda x:mail_rem.sub('',x))

In [ ]:
table.head()

Body  Label
0  save up to 70% on life insurance.why spend mor...      1
1  1) fight the risk of cancer! slim down - guara...      1
2  1) fight the risk of cancer! slim down - guara...      1
3  ##############################################...      1
4  i thought you might like these:1) slim down - ...      1

In [ ]:
#importing string libraries
import string

In [ ]:
#defining the function 'punc' for removing punctuation marks in a particular text

def punc(text):
  for i in string.punctuation:
    text=text.replace(i,'')
  return text

In [ ]:
#now applying function 'punc' in all data in the Body column

table['Body']=table['Body'].apply(punc)

In [ ]:
table.head()

Body  Label
0  save up to 70 on life insurancewhy spend more ...      1
1  1 fight the risk of cancer slim down  guarante...      1
2  1 fight the risk of cancer slim down  guarante...      1
3                                                ...      1
4  i thought you might like these1 slim down  gua...      1

In [ ]:
#there are many data in Body column written as 'empty'. As it is irrelevent so I am dropping all the rows with Body column is written as 'empty'

for i in table.index:
  if table['Body'][i] == 'empty':
    table.drop(i,inplace=True)

In [ ]:
table

Body  Label
0     save up to 70 on life insurancewhy spend more ...      1
1     1 fight the risk of cancer slim down  guarante...      1
2     1 fight the risk of cancer slim down  guarante...      1
3                                                   ...      1
4     i thought you might like these1 slim down  gua...      1
...                                                 ...    ...
6033  1 isilotm 325 for palm os pocket pc and window...      0
6034  effector       vol 15 no 35       november 8 2...      0
6039  we have extended our free seat sale until thur...      0
6042                                                ...      0
6043  in this issue01 readers write02 extension sear...      0

[5513 rows x 2 columns]

In [ ]:
#now defining a function 'num_remover' using string library for removing the digits in a string

def num_remover(text):
  for i in string.digits:
    text=text.replace(i,'')
  return text

In [ ]:
#now applying 'num_remover' function in the all Body column data

table['Body']=table['Body'].apply(num_remover)

In [ ]:
table.head()

Body  Label
0  save up to  on life insurancewhy spend more th...      1
1   fight the risk of cancer slim down  guarantee...      1
2   fight the risk of cancer slim down  guarantee...      1
3                                                ...      1
4  i thought you might like these slim down  guar...      1

In [ ]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [ ]:
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

In [ ]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
def stop_remover(text):
  new_text=[]
  for i in text.split():
    if i not in stopwords.words('english'):
      new_text.append(i)
  return " ".join(new_text)

In [ ]:
ps = PorterStemmer()

In [ ]:
def stemmer(text):
  new_text=[]
  for i in text.split():
    i = ps.stem(i)
    new_text.append(i)
  return " ".join(new_text)

In [ ]:
#removing all the stopword in all the data
table['Body']=table['Body'].apply(stop_remover)
#applying stemming in all word in all data
table['Body']=table['Body'].apply(stemmer)

In [ ]:
table.head()

Body  Label
0  save life insurancewhi spend tolif quot saving...      1
1  fight risk cancer slim guarante lose lb day ge...      1
2  fight risk cancer slim guarante lose lb day ge...      1
3  adult club offer free membership instant acces...      1
4  thought might like slim guarante lose lb day f...      1

In [ ]:
table.shape

(5513, 2)

In [ ]:
#exporting the final table after changes
table.to_csv('final.csv',index=False)

In [ ]:
#importing test train split
from sklearn.model_selection import train_test_split

In [ ]:
#importing the bag of words
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
cv = CountVectorizer(max_features=50000)

In [ ]:
#dividing the data

X = table['Body']
y = table['Label']

In [ ]:
#splitting the X and y data into train and test data with test_size=0.2 and random_state=2

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,random_state=0)

In [ ]:
print(X_train.shape, X_test.shape)

(4410,) (1103,)


In [ ]:
#fitting and transforming the X_train data
X_train_bow = cv.fit_transform(X_train).toarray()

#transforming the X_test
X_test_bow = cv.transform(X_test).toarray()

In [ ]:
len(cv.vocabulary_)

50000

In [ ]:
#importing all naive bayes classifier
from sklearn.naive_bayes import GaussianNB, BernoulliNB, MultinomialNB

**Checking with Gaussian naive bayes classifier**

In [ ]:
gnb=GaussianNB()

* Fitting the data

In [ ]:
model = gnb.fit(X_train_bow,y_train)

* Prediction of training and testing data

In [ ]:
y_train_pred=model.predict(X_train_bow)
y_test_pred=model.predict(X_test_bow)

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score,f1_score, roc_auc_score

* Train Data Accuracy

In [ ]:
accuracy_score(y_train, y_train_pred)

0.9886621315192744

In [ ]:
precision_score(y_train,y_train_pred)

0.9615088529638183

In [ ]:
f1_score(y_train,y_train_pred)

0.9803767660910518

In [ ]:
confusion_matrix(y_train, y_train_pred)

array([[3111,   50],
       [   0, 1249]])

* Test Data Accuracy

In [ ]:
accuracy_score(y_test, y_test_pred)

0.9356300997280145

In [ ]:
precision_score(y_test,y_test_pred)

0.9057239057239057

In [ ]:
f1_score(y_test,y_test_pred)

0.8834154351395731

In [ ]:
confusion_matrix(y_test, y_test_pred)

array([[763,  28],
       [ 43, 269]])

**Checking with bernoulli naive bayes classifier**

In [ ]:
bnb=BernoulliNB()

In [ ]:
model_bnb=bnb.fit(X_train_bow, y_train)

* Prediction of training and testing data

In [ ]:
y_train_bnb=model_bnb.predict(X_train_bow)
y_test_bnb=model_bnb.predict(X_test_bow)

* Train Data Accuracy

In [ ]:
accuracy_score(y_train, y_train_bnb)

0.9233560090702948

In [ ]:
precision_score(y_train,y_train_bnb)

0.9882100750267953

In [ ]:
f1_score(y_train,y_train_bnb)

0.845096241979835

In [ ]:
confusion_matrix(y_train, y_train_bnb)

array([[3150,   11],
       [ 327,  922]])

* Test Data Accuracy

In [ ]:
accuracy_score(y_test, y_test_bnb)

0.9066183136899365

In [ ]:
precision_score(y_test,y_test_bnb)

0.9906103286384976

In [ ]:
f1_score(y_test,y_test_bnb)

0.8038095238095239

In [ ]:
confusion_matrix(y_test, y_test_bnb)

array([[789,   2],
       [101, 211]])

**Checking with multinomial naive bayes classifier**

In [ ]:
mnb=MultinomialNB()

In [ ]:
model_mnb=mnb.fit(X_train_bow, y_train)

* Prediction of training and testing data

In [ ]:
y_train_mnb=model_mnb.predict(X_train_bow)
y_test_mnb=model_mnb.predict(X_test_bow)

* Train Data Accuracy

In [ ]:
accuracy_score(y_train, y_train_mnb)

0.9934240362811791

In [ ]:
precision_score(y_train, y_train_mnb)

0.9959349593495935

In [ ]:
f1_score(y_train, y_train_mnb)

0.9883017345703913

In [ ]:
confusion_matrix(y_train, y_train_mnb)

array([[3156,    5],
       [  24, 1225]])

* Test Data Accuracy

In [ ]:
accuracy_score(y_test, y_test_mnb)

0.9746146872166818

In [ ]:
precision_score(y_test,y_test_mnb)

0.9829931972789115

In [ ]:
f1_score(y_test,y_test_mnb)

0.9537953795379538

In [ ]:
confusion_matrix(y_test, y_test_mnb)

array([[786,   5],
       [ 23, 289]])

In [ ]:
model_mnb.predict_proba(X_test_bow)[:,1]

array([2.14415773e-03, 4.86669911e-36, 1.00000000e+00, ...,
       8.10246989e-08, 6.98883361e-17, 1.42393855e-02])

In [ ]:
roc_auc_score(y_test,model_mnb.predict_proba(X_test_bow)[:,1])

np.float64(0.9904129793510325)

****

After Checking with all Gaussian, Bernoulli and Multinomial naive bayes classifier, \
We got that the Multinomial naive bayes had its test data accuracy above 97% and precision above 98% and f1 score is 95% and ROC-AUC score as 99% which is excellent. \
That is why the final model selected is **Multinomial naive bayes classifier**

****

Now checking some random mail by using the final model

* Checking with an random normal email content

In [ ]:
mail = "Hey! this is Arnav here, I made this model for a email spam classifier. I made this project on 22-10-2023, Sunday. I really wanted you to take a look on this model and a review on this model will be appreciated.\n Regards Arnav"

In [ ]:
#performing all the task that we perform earlier in the Body column so that we can normalize the given text and make it easy to vectorized

mail = mail.lower()
mail = newline_rem.sub('',mail)
mail = remove_url.sub('',mail)
mail = mail_rem.sub('',mail)
mail = punc(mail)
mail = num_remover(mail)
mail = stop_remover(mail)
mail = stemmer(mail)
mail = cv.transform([mail]).toarray()

In [ ]:
prediction=model_mnb.predict(mail)
if prediction[0]==1:
  print("Spam")
else:
  print("Not spam")

Not spam


* Taking a spam from my G-mail id for cheking

In [ ]:
mail2="At makeO we value your safety, satisfaction, and convenience at the utmost. Our commitment to excellence is evident in every aspect of our services. Let's embark on a journey towards wellness and beauty that's safe, personalized, and hassle-free. Should you have any questions or wish to explore our services, don't hesitate to reach out. To your health and happiness.\n Download our makeO app for bookings, support, and more info Click this link https://c.webengage.com/lw/g1.jpgp=eyJsYyI6ImFhMTMxYzg0IiwibCI6IjAwMDAwMTg5LWI4ZDgtZjIyMy04Y2ZkLTA0NjE2OTQ2ZTU3ZCIsImMiOiIzMTMzNTMzIiwiZW0iOiJhelczME85cjdlU3NYaW5rUU9mNHFLS2VLRmNQMHY3K2NHSXZ2a2MrSEUwPSIsImUiOiJ%2BM2JjZmRtNiIsInYiOiI0NHBpamRvIiwicyI6IjMxYjkxNDNlYWNjMTE1Ml8yYWZiODI2Ni1hMzA5LTRhYjctYjJkZC1hYjlmZjhiNzk4NGI6MTY5NzE4OTY2MTU0OCIsImV2ZW50IjoiZW1haWxfY2xpY2siLCJjdGEiOiI4OTE1ZThjZSIsInRvVVJMIjoiaHR0cHM6Ly9tYWtlby5hcHAvdG9vdGhzaT91dG1fc291cmNlPWVtYWlsJnV0bV9tZWRpdW09ZW1haWwmdXRtX2NhbXBhaWduPXdhcm11cF90b290aHNpXzUifQ%3D%3D"

In [ ]:
#performing all the task that we perform earlier in the Body column so that we can normalize the given text and make it easy to vectorized

mail2 = mail2.lower()
mail2 = newline_rem.sub('',mail2)
mail2 = remove_url.sub('',mail2)
mail2 = mail_rem.sub('',mail2)
mail2 = punc(mail2)
mail2 = num_remover(mail2)
mail2 = stop_remover(mail2)
mail2 = stemmer(mail2)
mail2 = cv.transform([mail2]).toarray()

In [ ]:
pred = model_mnb.predict(mail2)
if pred[0]==1:
  print("Spam")
else:
  print("Not spam")

Spam


In [ ]:
#defining the function for basic text preprocessing for a particular text
def transform_text(text):
  text = text.lower()
  text = newline_rem.sub('',text)
  text = remove_url.sub('',text)
  text = mail_rem.sub('',text)
  text = punc(text)
  text = num_remover(text)
  text = stop_remover(text)
  text = stemmer(text)
  return text

In [ ]:
import pickle

In [ ]:
#exporting both 'model_mnb' and 'cv' using pickle dump
pickle.dump(cv, open('vectorizer.pkl','wb'))
pickle.dump(model_mnb, open('mnb_model.pkl','wb'))

Testing model with another random text

In [ ]:
input = "Life is a bit uncertain, you never know what can happen to your loved once, taking a life insurance is the best thing you can do your loved. In our company we provide you an excellent insurance offer upto 1 crore, now we have speacial offer due to festive season, click this link https://www.google.com/search?q=sa+vs+ban&rlz=1C1VDKB_enIN967IN967&oq=sa+vs&gs_lcrp=EgZjaHJvbWUqDwgEEAAYQxiDARixAxiKBTILCAAQRRgnGDsYigUyDwgBEEUYORiDARixAxiABDIGCAIQRRg7MgkIAxAjGCcYigUyDwgEEAAYQxiDARixAxiKBTIGCAUQRRg9MgYIBhBFGD0yBggHEEUYPdIBCDQxNjhqMGo3qAIAsAIA&sourceid  to grab this deal offer valid till end of this week."

In [ ]:
#now using transform_text function
input = transform_text(input)
input = cv.transform([input]).toarray()
pred = model_mnb.predict(input)
if pred[0]==1:
  print('Spam')
else:
  print('Not spam')

Spam


In [ ]:
input="Congratulations! 🎉 You have won $1,000,000 in the International Mega Lottery. To claim your prize, please send your bank account details immediately."
input = transform_text(input)
input = cv.transform([input]).toarray()
pred = model_mnb.predict(input)
if pred[0]==1:
  print('Spam')
else:
  print('Not spam')

Spam


In [ ]:
import pickle

In [ ]:
model1=pickle.load(open('mnb_model (1).pkl','rb'))

In [ ]:
cv1=pickle.load(open('vectorizer.pkl','rb'))

In [ ]:
input = "Life is a bit uncertain, you never know what can happen to your loved once, taking a life insurance is the best thing you can do your loved. In our company we provide you an excellent insurance offer upto 1 crore, now we have speacial offer due to festive season, click this link https://www.google.com/search?q=sa+vs+ban&rlz=1C1VDKB_enIN967IN967&oq=sa+vs&gs_lcrp=EgZjaHJvbWUqDwgEEAAYQxiDARixAxiKBTILCAAQRRgnGDsYigUyDwgBEEUYORiDARixAxiABDIGCAIQRRg7MgkIAxAjGCcYigUyDwgEEAAYQxiDARixAxiKBTIGCAUQRRg9MgYIBhBFGD0yBggHEEUYPdIBCDQxNjhqMGo3qAIAsAIA&sourceid  to grab this deal offer valid till end of this week."
#now using transform_text function
input = transform_text(input)
input = cv1.transform([input]).toarray()
pred = model1.predict(input)
if pred[0]==1:
  print('Spam')
else:
  print('Not spam')

Spam
